/*
 * Copyright 2012 Amadeus s.a.s.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// var Aria = require("../Aria");
// var ariaUtilsString = require("../utils/String");
import { Observable, Subject } from "rxjs";
import { RootStatement, Statement } from "./TreeBeans.js";
import { Callback } from "../core/CfgBeans.js";
import { stringify } from "../utils/String.js";
import { FRAMEWORK_PREFIX } from "../Aria.js";

export interface DependencySpec {
  library: string;
  importedItem: string;
}

/**
 * Writer object used to manage the JavaScript output generated by template statements
 */
export class ClassWriter {
  /**
   * TODO:ModernAria: Modify Comment
   * Callback used to process a single statement in the content
   * @protected
   */
  protected _processStatementSubject = new Subject<Statement>();
  public processStatement$ = this._processStatementSubject.asObservable();

  /**
   * Callback used to process errors
   * @type aria.core.CfgBeans:Callback
   * @protected
   */
  protected _processErrorsSubject: Subject<unknown> | null = null;
  public processErrors$: Observable<unknown> | null = null;

  /**
   * Current indentation string. Used when writing a line
   * @protected
   */
  protected _curindent = "";

  /**
   * Text used for indentation (null to disable)
   */
  public indentUnit: string | null = " ";

  /**
   * Current working output block
   * @protected
   */
  protected _curblock: { curindentnbr: number; out: string[] } | null = null;

  /**
   * Counter for number of variables created. This is increased every time a new var statement is called and is
   * used as unique key.
   * @protected
   */
  protected _varNameNumber = 0;

  /**
   * Optional error context to be passed when logging errors
   */
  public errorContext: null | { [key: string]: unknown } = null;

  /**
   * if true, the dependencies section should even contain already loaded dependencies
   */
  public allDependencies = false;

  /**
   * Stores the template parameter
   */
  public templateParam: unknown | null = null;

  /**
   * Stores the parent class type
   */
  public parentClassType = "JS";

  /**
   * Stores the parent class name
   */
  public parentClassName: string | null = null;

  /**
   * Stores the parent classpath
   */
  public parentClasspath: string | null = null;

  /**
   * Stores the script class name
   */
  public scriptClassName = null;

  /**
   * Stores the script classpath
   */
  scriptClasspath: string | null = null;

  /**
   * Callback to call when generation is finished
   */
  callback: Callback | null = null;

  /**
   * Direct link to widget libraries
   * @type Object
   *
   * <pre>
   * {
   *     libName : libClasspath
   * }
   * </pre>
   */
  wlibs: { [key: string]: string } = {};

  /**
   * Map of declared macros
   * @type Object
   *
   * <pre>
   * {
   *     macroName : {
   *         definition : statement
   *     }
   * }
   * </pre>
   */
  macros: { [key: string]: { definition?: Statement } } = {};

  /**
   * Map of declared views
   * @type Object
   *
   * <pre>
   * {
   *    viewName : {
   *       firstDefinition : statement,
   *       nbParams : numberOfParameters
   *    }
   * }
   * </pre>
   */
  views: {
    [key: string]: {
      baseName: string;
      firstDefinition?: Statement;
      nbParams?: number;
    };
  } = {};

  /**
   * Map of possible output block
   * @type Object
   *
   * <pre>
   * {
   *    blockName : {
   *       curindentnbr : indent,
   *       out : []
   *    }
   * }
   * </pre>
   *
   * @protected
   */
  _blocks: { [key: string]: { curindentnbr: number; out: string[] } } = {};

  /**
   * Stack of output blocks
   * @type Array
   * @protected
   */
  _stack: { curindentnbr: number; out: string[] }[] = [];

  /**
   * Map of dependencies found for the class to be generated
   * @protected
   */
  // protected _dependencies: DependencySpec[] = [];
  protected _dependencies: Map<string, Set<string>> = new Map();

  /**
   * Contains information about errors which occured during the generation process. If the processErrors callback
   * is provided, the errors property contains a boolean indicating whether errors occurred or not. If the
   * processErrors callback is not provided, the errors property is null if no error occured, otherwise, it
   * contains the array of errors.
   */
  errors:
    | {
        msgId: string;
        msgArgs?: unknown[] | null;
        errorContext: null | { [key: string]: unknown };
      }[]
    | null
    | boolean = false;

  /**
   * Indicates if the writer has a mirror debug writer
   * @type Boolean
   */
  debug = false;

  /**
   * Tree structure generated by the parser
   * @type aria.templates.TreeBeans:Root
   */
  tree: RootStatement | null = null;

  /**
   * If set to true, code generation is disabled, only parsing matters.
   * @type Boolean
   */
  parseOnly = false;

  /**
   * If set to true, widget libraries will not be loaded during class generation.
   * @type Boolean
   */
  dontLoadWidgetLibs = false;

  /**
   * Create a Class Writer instance
   * @param {aria.core.CfgBeans:Callback} processStatement Callback used to process a single statement in the content
   * @param {aria.core.CfgBeans:Callback} processErrors Callback used to process errors. Can be omitted for default
   * error processing (appending errors to the errors array)
   */
  constructor(processErrors?: boolean) {
    if (processErrors) {
      this._processErrorsSubject = new Subject<unknown>();
      this.processErrors$ = this._processErrorsSubject.asObservable();
      this.errors = null;
    } else {
      this.errors = false;
    }
  }

  /**
   * Add a list of classpath dependencies
   * @param {Array} dependencies list of classpath
   * @param {String} extension dependencies extension (default: ".js")
   */
  public addDependencies(dependencies: DependencySpec[]): void {
    if (dependencies) {
      dependencies.forEach((dependency) => {
        this.addDependency(dependency);
      });
    }
  }

  /**
   * Add a single classpath dependency
   * @param {String} dependency classpath
   * @param {String} extension dependency extension (default: ".js")
   */
  addDependency(dependency: DependencySpec): void {
    // this._dependencies.push(dependency);
    if (!this._dependencies.has(dependency.library)) {
      this._dependencies.set(dependency.library, new Set<string>());
    }
    this._dependencies.get(dependency.library)?.add(dependency.importedItem);
  }

  /**
   * Writes the list of unique dependencies as a set of import statements in the current block.
   */
  writeDependencies() {
    // this._dependencies.forEach((dependency) => {
    //   this.writeln(`import { ${dependency.importedItem} } from '${dependency.library}';`);
    // });

    this._dependencies.forEach((importedItems, library) => {
      const items = Array.from(importedItems).join(", ");
      this.writeln(`import { ${items} } from '${library}';`);
    });
  }

  /**
   * Get a macro description
   * @param {String} macroName Name of the macro
   * @return {Object}
   */
  getMacro(macroName: string) {
    let res = this.macros[macroName];
    if (!res) {
      res = {};
      this.macros[macroName] = res;
    }
    return res;
  }

  /**
   * Write a line in the current output block. The line is built concatenating all arguments and appending a new
   * line character.
   * @param {String} One or more string to be written
   */
  writeln(...linesToWite: string[]) {
    const out = this._curblock?.out;
    if (!out) {
      //TODO:MordernAria:Current block is not set, throw/log errors?
      return;
    }

    if (this._curindent) {
      out.push(this._curindent);
    }
    out.push(...linesToWite);
    out.push("\n");
  }

  /**
   * Get a view description
   * @param {String} viewBaseName Name of the view
   * @return {Object}
   */
  getView(viewBaseName: string) {
    let res = this.views[viewBaseName];
    if (res == null) {
      res = {
        baseName: viewBaseName,
      };
      this.views[viewBaseName] = res;
    }
    return res;
  }

  /**
   * Whether the ClassWriter is ready to perform some output. This happens only after entering an output block
   * @return {Boolean}
   */
  isOutputReady() {
    return this._curblock != null;
  }

  /**
   * Create a new output block
   * @param {String} blockname Name of the block
   * @param {Number} indent Number of indentation unit to be used
   */
  newBlock(blockname: string, indent: number) {
    const newblock = {
      curindentnbr: indent,
      out: [],
    };
    this._blocks[blockname] = newblock;
  }

  /**
   * Enter an output block. Any output operation (write or writeln) will output it's content in this block
   * @param {String} blockname Name of the block
   */
  enterBlock(blockname: string) {
    if (!this._curblock) {
      return;
    }
    this._stack.push(this._curblock);
    this._curblock = this._blocks[blockname];
    if (this.indentUnit && this._curblock) {
      this._updateIndent();
    }
  }

  /**
   * Leave an output block and return to the previous block in the stack if any.
   */
  leaveBlock() {
    this._curblock = this._stack.pop() || null;
    if (this.indentUnit && this._curblock) {
      this._updateIndent();
    }
  }

  /**
   * Get the clock's content
   * @param {String} blockname Name of the block
   * @return {String} output content
   */
  getBlockContent(blockname: string) {
    return this._blocks[blockname].out.join("");
  }

  //         /**
  //          * Convert an expression into a string
  //          * @see aria.utils.String.stringify
  //          * @param {Object} expression Expression to be converted into a string
  //          * @return {String}
  //          */
  //         stringify : ariaUtilsString.stringify,

  /**
   * Create a new unique var name
   * @return {String} name of the variable
   */
  newVarName() {
    this._varNameNumber++;
    return "__v_" + this._varNameNumber;
  }

  /**
   * Start processing the content of a tree node (list of aria.templates.TreeBeans.Statement)
   * @param {Array} content list of statements
   */
  processContent(content: Statement[]) {
    for (let i = 0; i < content.length; i++) {
      this.processStatement(content[i]);
    }
  }

  /**
   * Process a statement calling the callback defined in the constructor
   * @param {aria.templates.TreeBeans:Statement} statement Statement to be processed
   */
  processStatement(statement: Statement) {
    this._processStatementSubject.next(statement);
  }

  /**
   * Update the current indentation for the output block.
   * @protected
   */
  _updateIndent() {
    this._curindent = new Array(1 + this._curblock!.curindentnbr).join(
      this.indentUnit || ""
    );
  }

  /**
   * Log an error calling the error callback defined in the constructor.
   * @param {aria.templates.TreeBeans:Statement} statement Statement generating the error
   * @param {String} msgId Message to be logged
   * @param {Array} msgArgs List of error parameters as in jsObject.$logError
   */
  logError(statement: Statement, msgId: string, msgArgs?: unknown[] | null) {
    if (this._processErrorsSubject) {
      this.errors = true;
      this._processErrorsSubject.next({
        statement,
        msgId,
        msgArgs,
        errorContext: this.errorContext,
      });
    } else {
      if (!msgArgs) {
        msgArgs = [];
      }
      if (this.errors === null || typeof this.errors === "boolean") {
        this.errors = [];
      }
      msgArgs.push(statement.lineNumber);
      this.errors!.push({
        msgId: msgId,
        msgArgs: msgArgs,
        errorContext: this.errorContext,
      });
    }
  }

  /**
   * Log an error without stopping the template processing.
   * @param {aria.templates.TreeBeans:Statement} statement Statement generating the error
   * @param {String} msgId Message to be logged
   * @param {Array} msgArgs List of error parameters as in jsObject.$logError
   */
  logWarn(statement: Statement, msgId: string, msgArgs?: unknown[] | null) {
    if (msgArgs == null) {
      msgArgs = [];
    }
    msgArgs.push(statement.lineNumber);
    console.warn(msgId, msgArgs, this.errorContext);
    //TODO:ModernAria: Implement JS Object class with logging methods
    // this.$logWarn(msgId, msgArgs, this.errorContext);
  }

  /**
   * Increase the block indent of one unit
   */
  increaseIndent() {
    if (this.indentUnit) {
      // TODO:ModernAria:Should Throw error/warning _curblock should not be null??
      // HIGHLIGHT:ModernAria:Catch gaps in the code
      this._curblock && this._curblock.curindentnbr++;
      this._curindent += this.indentUnit;
    }
  }

  /**
   * Decrease the block indent of one unit
   */
  decreaseIndent() {
    if (this.indentUnit) {
      // TODO:ModernAria:Should Throw error/warning _curblock should not be null??
      // HIGHLIGHT:ModernAria:Catch gaps in the code
      this._curblock && this._curblock.curindentnbr--;
      this._updateIndent();
    }
  }

  /**
   * Write in the current output block. The text written is built concatenating all arguments.
   * @param {String} One or more string to be written
   */
  write(...strings: string[]) {
    const out = this._curblock?.out;
    out?.push(...strings);
  }

  /**
   * Wrap an expression evaluation in a try catch and return result
   * @param {String} exprStr String to be eval'ed
   * @param {aria.templates.TreeBeans:Statement} statement Statement corresponding to the expression
   * @param {String} errorMsg Message to be logged in case of errors
   * @return {String} container the name of the variable that will contain the expression
   */
  wrapExpression(exprStr: string, statement: Statement, errorMsg: string) {
    const container = this.newVarName();

    // stringify the expression for the eval
    exprStr = stringify(exprStr);
    this.writeln("var " + container + " = null;");
    this.writeln("try {");
    this.increaseIndent();
    // remove quotes
    exprStr = exprStr.substring(1, exprStr.length - 1);
    this.writeln('eval( "' + container + "=(" + exprStr + ')" );');
    this.decreaseIndent();
    this.writeln("} catch (e) {");
    this.increaseIndent();
    this.writeln(
      "this.$logError(",
      errorMsg,
      ',["',
      exprStr,
      '",__filename,',
      statement.lineNumber.toString(),
      ",",
      stringify(statement.name),
      "], e);"
    );
    this.decreaseIndent();
    this.writeln("}");

    return container;
  }

  /**
   * Add a statement to store line number (use to track runtime exceptions)
   * @param {Number} lineNumber
   */
  trackLine(lineNumber: number) {
      if (this._curblock) {
          this.writeln("this['" + FRAMEWORK_PREFIX + "currentLineNumber'] = " + lineNumber + ";");
      }
  }

  //         /**
  //          * Set the parseOnly flag to true and disables functions which are only useful for class generation.
  //          */
  //         enableParseOnly : function () {
  //             this.parseOnly = true;
  //             // disables functions which are only useful to generate code:
  //             var empty = Aria.empty;
  //             this.writeDependencies = empty;
  //             this.newVarName = empty;
  //             this.writeln = empty;
  //             this.write = empty;
  //             this.wrapExpression = empty;
  //             this.trackLine = empty;
  //         }
}

//     },
//     $prototype : {
//

//     }
// });
