/* eslint-disable @typescript-eslint/no-explicit-any */
//TODO:ModernAria: Rremove the esline disable
import { indexOfNotEscaped, stringify } from "../utils/String.js";
import { ClassWriter } from "./class-writer.js";
import { Statement } from "./tree-beans.js";

/*
 * Copyright 2012 Amadeus s.a.s.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// var Aria = require("../Aria");
// var ariaUtilsString = require("../utils/String");
// var ariaTemplatesModifiers = require("./Modifiers");
// require("../utils/Path");
// var ariaUtilsDelegate = require("../utils/Delegate");
// var ariaUtilsType = require("../utils/Type");
// var ariaCoreEnvironmentEnvironment = require("../core/environment/Environment");
// var ariaCoreAppEnvironment = require("../core/AppEnvironment");

/**
 * Counter for the generation of unique macro names for sections used as containers
 * @type Number
 * @private
 */
let counter = 0;

// /**
//  * Prefix for the automatic generation of macro names for sections used as containers
//  * @type String
//  * @private
//  */
const automaticMacroPrefix = "__$autoGenerated__";

/**
 * Counter that allows to understand if an automatic inline macro is being generated for a section that is used without
 * container. In that case, it is greater than 0
 * @type Number
 * @private
 */
let automaticMacroCounter = 0;

/**
 * List of variables that are defined in section contents (when sections are used as containers). It is used for
 * creating var statements at the end of each real macro in order to give the correct visibility to these variables
 * @type Array
 * @private
 */
let globalMacroVariables: string[] = [];

/**
 * Name of the actual macro that is being processed
 * @type String
 * @private
 */
let currentMacroName = "";

// TODO:MODERN_ARIA:Implement and use Aria.FRAMEWORK_PREFIX root aria.js file
const FRAMEWORK_PREFIX= "aria:";


/**
 * Template statements. Note that root statements are special ones and are not included here.
 */
// module.exports = Aria.classDefinition({
//     $classpath : "aria.templates.Statements",
//     $singleton : true,
//     $statics : {
        // ERROR MESSAGES:
        const SHOULD_BE_IN_MACRO = "line %2: Template error: statement '%1' cannot be used out of a macro.";
        const TEMPLATE_STATEMENT_MISUSED = "Template error: the '%1' statement is misused, it should only be used as the root statement in a template.";
        const ELSE_WITHOUT_IF = "line %1: Template error: 'else' or 'elseif' is used outside an 'if' structure.";
        const ELSEIF_AFTER_ELSE = "line %1: Template error: 'elseif' is used after 'else' in the same 'if' structure.";
        const ELSE_ALREADY_USED = "line %1: Template error: an 'else' statement has already been used in this 'if' structure.";
        const INVALID_WIDGET_SYNTAX = "line %1: Template error: invalid syntax for the widget statement; expected syntax: @lib:widget";
        const UNDECLARED_WIDGET_LIBRARY = "line %2: Template error: found widget library '%1', which is undeclared in the wlibs parameter of the 'Template' statement.";
        const INVALID_MODIFIER_SYNTAX = "line %2: Template error: invalid modifier syntax '%1'.";
        const UNKNOWN_WIDGET = "line %2: Template error: unknown widget '%1'.";
        const MACRO_ALREADY_DEFINED = "line %3: Template error: macro '%1' is already defined line %2.";
        const SEPARATOR_NOT_FIRST_IN_FOREACH = "line %1: Template error: the separator statement can only be used as the first statement inside a {foreach ...} ... {/foreach} loop.";
        const INCOMPATIBLE_CREATEVIEW = "line %2: Template error: two createView statements with the same view base name must have the same depth (previous definition line %1).";
        const INCORRECT_VARIABLE_NAME = "line %2: Template error: incorrect variable name '%1'.";
        // const INVALID_FOREACH_INKEYWORD = "line %2: Template error: invalid foreach syntax, expected one of 'in', 'inView', 'inFilteredView', 'inSortedView', 'inPagedView' but found: '%1'.";
        // const INVALID_WIDGET_LIBRARY = "line %3: Template error: %1 (%2) is not a valid widget library. A widget library must extend aria.widgetLibs.WidgetLib.";
        // const INVALID_EVENT_TYPE = "The event type: '%1' is an invalid event type.";
        // const SECTIONS_AS_CONTAINERS = "Sections as container statements ({section {...}}...{/section}) have been allowed through the application environment. Nevertheless, it is strongly advisable to use them as self-closing statements ({section {...}/}).";
    // },
    // $constructor : function () {
    //     var utilString = ariaUtilsString;
    //     var modifiers = ariaTemplatesModifiers;
    //     var statementsSingleton = this;

        // Root statements are processed differently from other statements (they are processed directly without going
        // through ALLSTATEMENT), so if the process method is called, it means the statement was misused):
        // TODO:MODERN_ARIA:Type definition of out instead of any
        export const rootStatement = {
            inMacro : false,
            container : true,
            process : function (out: ClassWriter, statement: Statement) {
                return out.logError(statement, TEMPLATE_STATEMENT_MISUSED, [statement.name]);
            }
        };

        export const ALLSTATEMENTS = {
            "Template" : rootStatement,
            "Library" : rootStatement,
            "CSSTemplate" : rootStatement,
            "CSSLibrary" : rootStatement,
            "TextTemplate" : rootStatement,
            "#TEXT#" : {
                container : false,
                // TODO:MODERN_ARIA:Type definition of out instead of any
                process : function (out: ClassWriter, statement: Statement) {
                    if (out.isOutputReady()) {
                        const param = stringify(statement.paramBlock);
                        out.writeln("this.__$write(", param, ",", `${statement.lineNumber}`, ");");
                    } else {
                        // check if text contains something
                        if (statement.paramBlock.replace(/[ \t\r\n]+/gm, "") !== '') {
                            out.logError(statement, SHOULD_BE_IN_MACRO, ["#TEXT# - "
                                    + statement.paramBlock]);
                        }
                    }
                }
            },
            // TODO:MODERN_ARIA:Type definition of out instead of any
            "#CDATA#" : {
                inMacro : true,
                container : false,
                process : function (out: ClassWriter, statement: Statement) {
                    const param = stringify(statement.paramBlock);
                    out.writeln("this.__$write(", param, ",", `${statement.lineNumber}`, ");");
                }
            },
            "#EXPRESSION#" : {
                inMacro : true,
                container : false,
                process : function (out: ClassWriter, statement: Statement, classGenerator: ClassGenerator) {
                    let param = statement.paramBlock;
                    let nextPipe = indexOfNotEscaped(param, "|");
                    const parts: string[] = [];
                    // split param against unescaped |
                    while (nextPipe != -1) {
                        parts.push(param.substring(0, nextPipe));
                        param = param.substring(nextPipe + 1);
                        nextPipe = indexOfNotEscaped(param, "|");
                    }
                    parts.push(param);

                    // Automatic escape ----------------------------------------

                    let autoEscape = false;

                    // We automatically escape expressions if needed, using the feature of modifiers, since the
                    // escape is already handled by a modifier itself.
                    // For safety and logical reasons, the escaping is done at the end, so the modifier is added as
                    // the last one.
                    // There are two cases where we don't do it automatically:
                    // - in CSS templates
                    // - if the modifier is already present at the end of the list, in which case the user gets
                    // control back on how to apply the final escape

                    let escapeModifierName = classGenerator.escapeModifier; // Gets the actual name of the modifier
                    // in this context

                    if (escapeModifierName != null) {
                        // TODO:ModernAria:Type definition of out.templateParam in expressions
                        // eslint-disable-next-line @typescript-eslint/no-explicit-any
                        let escapeByDefault: boolean | null = (out.templateParam as any).$escapeHtmlByDefault;
                        if (escapeByDefault == null) {
                            //TODO:MODERN_ARIA:Process esccapeHtmlByDefault and implement modifiers
                            // escapeByDefault = ariaCoreEnvironmentEnvironment.hasEscapeHtmlByDefault(out.templateParam.$classpath);
                            escapeByDefault = false;
                        }
                        if (escapeByDefault) {
                            escapeModifierName = escapeModifierName.toLowerCase();

                            if (parts[parts.length - 1].toLowerCase().indexOf(escapeModifierName) < 0) {
                                parts.push(escapeModifierName);
                                autoEscape = true;
                            }
                        }

                    }

                    // end of: automatic escape --------------------------------


                    const modifiersList: string[] = [];
                    const beginexpr: string[] = [];
                    const endexpr: string[] = [];
                    let expr;
                    // TODO:ModernAria: Process modifiers (pipes) in expressions
                    // var regExp = /^(\w+)(?::([\s\S]*))?$/;
                    // for (var i = parts.length - 1; i >= 1; i--) {
                    //     var modifier = parts[i]; // e.g. default:"param"
                    //     var match = regExp.exec(modifier); // something like ['default:"param"', "default", '"param"']
                    //     if (!match) {
                    //         return out.logError(statement, INVALID_MODIFIER_SYNTAX, [modifier]);
                    //     }
                    //     var modifierName = match[1];
                    //     // init the modifier, for example add a dependency
                    //     modifiers.initModifier(modifierName, out);
                    //     beginexpr.push("this.$modifier('" + modifierName + "',[");
                    //     expr = match[2]; // parameters of the modifier
                    //     if (expr) {
                    //         endexpr[i] = ", " + expr + "])";
                    //     } else {
                    //         endexpr[i] = "])";
                    //     }
                    //     modifiersList.unshift({
                    //         name: modifierName,
                    //         args: expr
                    //     });
                    // }
                    expr = parts[0];
                    if (autoEscape) {
                        // don't include the automatically added escape modifier in the tree
                        modifiersList.pop();
                    }
                    statement.properties  = {
                        expression: expr,
                        modifiers: modifiersList
                    };
                    beginexpr.push(expr);

                    // merge final expression
                    expr = beginexpr.concat(endexpr).join('');

                    if (out.debug) {
                        expr = out.wrapExpression(expr, statement, "this.EXCEPTION_IN_EXPRESSION");
                    }
                    out.writeln("this.__$write(", expr, ",", `${statement.lineNumber}`, ");");
                }
            },
            "separator" : {
                inMacro : true,
                container : true,
                paramRegexp : /^$/,
                process : function (out: ClassWriter, statement: Statement) {
                  // TODO:ModernAria: Need specific type definitions for statements
                  if(!statement.parent) {
                    return;
                  }
                  const foreachStruct = statement.parent;


                  // allow text before the foreach for the Txt templates
                  const okStruct = foreachStruct.content && (foreachStruct.content[0] === statement || (foreachStruct.content[1] === statement && foreachStruct.content[0].name === "#TEXT#"));
                  if (foreachStruct.name !== "foreach" || !okStruct) {
                      out.logError(statement, SEPARATOR_NOT_FIRST_IN_FOREACH);
                      return;
                  }
                  const variterct: string = (foreachStruct as any)[FRAMEWORK_PREFIX + 'foreachCounter'];
                  out.writeln("if (", variterct, ">1) {");
                  out.increaseIndent();
                  statement.content && out.processContent(statement.content);
                  out.decreaseIndent();
                  out.writeln("}");
                }
            },
            "id" : {
                inMacro : true,
                container : false,
                paramRegexp : /^\s*(\S[\s\S]*)\s*$/,
                process : function (out: ClassWriter, statement: Statement, param: string[]) {
                    const userId = param[0];
                    out.writeln('this.__$writeId(', userId, ",", statement.lineNumber, ');');
                    statement.properties = {
                        id: userId
                    };
                }
            },
            // "on" : {
            //     inMacro : true,
            //     container : false,
            //     paramRegexp : /^(\w+)\s+([\s\S]+)$/,
            //     process : function (out, statement, param) {
            //         const eventName = param[1];
            //         const callback = param[2];
            //         const delegate = ariaUtilsDelegate;
            //         var eventDependencies = delegate.delegatedGestures[eventName];
            //         if (eventDependencies) {
            //             out.addDependency(eventDependencies);
            //         }
            //         if (!delegate.supportedEvents[eventName]) {
            //             out.logWarn(statement, statementsSingleton.INVALID_EVENT_TYPE, [eventName]);
            //         }
            //         out.writeln("this.__$statementOnEvent(", out.stringify(eventName), ",this.$normCallback(", callback, "),", statement.lineNumber, ');');
            //         statement.properties = {
            //             eventName: eventName,
            //             callback: callback
            //         };
            //     }
            // },
            "if" : {
                inMacro : true,
                container : true,
                process : function (out, statement) {
                    const param = statement.paramBlock;
                    out.writeln("if (", param, ") {");
                    out.increaseIndent();
                    out.processContent(statement.content);

                    // clean statement in case of reprocessing of the tree
                    delete statement[FRAMEWORK_PREFIX + "elsepresent"];

                    out.decreaseIndent();
                    out.writeln("}");
                }
            },
            "elseif" : {
                inMacro : true,
                container : false,
                process : function (out: ClassWriter, statement: Statement) {
                    const param = statement.paramBlock;
                    const ifstruct = statement.parent as Statement;
                    if (ifstruct.name != "if") {
                        return out.logError(statement, ELSE_WITHOUT_IF);
                    }
                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                    if ((ifstruct as any)[FRAMEWORK_PREFIX + "elsepresent"]) {
                        return out.logError(statement, ELSEIF_AFTER_ELSE);
                    }
                    out.decreaseIndent();
                    out.writeln("} else if (", param, ") {");
                    out.increaseIndent();
                }
            },
            "else" : {
                inMacro : true,
                container : false,
                paramRegexp : /^$/, /* no parameter for else */
                process : function (out: ClassWriter, statement: Statement) {
                    const ifstruct = statement.parent as Statement;
                    if (ifstruct.name != "if") {
                        return out.logError(statement, ELSE_WITHOUT_IF);
                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                    } else if ((ifstruct as any)[FRAMEWORK_PREFIX + "elsepresent"]) {
                        return out.logError(statement, ELSE_ALREADY_USED);
                    }
                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                    (ifstruct as any)[FRAMEWORK_PREFIX + "elsepresent"] = true;
                    out.decreaseIndent();
                    out.writeln("} else {");
                    out.increaseIndent();
                }
            },
            // "createView" : {
            //     inMacro : undefined, /* may be either in or out of a macro */
            //     container : false,
            //     // syntax: createView myView[param1][param2] on myArray
            //     paramRegexp : /^([_\w]+)(\[([^\[\]]+(\]\[[^\[\]])*)\])?\s+on\s+([\s\S]+)$/,
            //     process : function (out, statement, param) {
            //         const viewBaseName = param[1];
            //         // TODO:ModernAria: Implement isJsReservedWord and check if error handling is needed
            //         // if (Aria.isJsReservedWord(viewBaseName)) {
            //         //     return out.logError(statement, statementsSingleton.INCORRECT_VARIABLE_NAME, [viewBaseName]);
            //         // }
            //         // TODO:ModernAria: Typings and let and const changes, understand better
            //         let viewParametersString: string = param[3];
            //         const viewArray = param[5];
            //         let viewParametersArray = [];
            //         let numberOfParameters = 0;
            //         if (viewParametersString) {
            //             viewParametersArray = viewParametersString.split('][');
            //             numberOfParameters = viewParametersArray.length;
            //             viewParametersString = ['[(', viewParametersArray.join('),('), ')]'].join('');
            //         } else {
            //             viewParametersString = "[]";
            //         }
            //         const view = out.getView(viewBaseName);
            //         if (view.firstDefinition) {
            //             // check the number of parameters, which must be the same for a given view base name
            //             // through the whole template
            //             if (view.nbParams != numberOfParameters) {
            //                 out.logError(statement, INCOMPATIBLE_CREATEVIEW, [view.firstDefinition.lineNumber]);
            //                 return;
            //             }
            //         } else {
            //             view.firstDefinition = statement;
            //             view.nbParams = numberOfParameters;
            //         }
            //         // TODO: ModernAria: Hanndle this add dependency
            //         out.addDependency("aria.templates.View"); // dependency on the view object
            //         const isGlobal = !out.isOutputReady();
            //         if (isGlobal) {
            //             out.enterBlock("globalVars");
            //         }
            //         out.writeln(isGlobal ? "this." : "var ", viewBaseName, "=this.__$createView(", out.stringify(viewBaseName), ",", viewParametersString, ",(", viewArray, "));");
            //         if (isGlobal) {
            //             out.leaveBlock();
            //         }
            //         statement.properties = {
            //             view: view,
            //             parameters: viewParametersString,
            //             array: viewArray
            //         };
            //     }
            // },
            "for" : {
                inMacro : true,
                container : true,
                process : function (out: ClassWriter, statement: Statement) {
                    // TODO: check parameter to avoid code injection and make debugging easier?
                    out.writeln("for (", statement.paramBlock, ") {");
                    out.increaseIndent();
                    statement.content && out.processContent(statement.content);
                    out.decreaseIndent();
                    out.writeln("}");
                }
            },
            "foreach" : {
                inMacro : true,
                container : true,
                // syntax: foreach varname in mymap
                // or : foreach varname inArray myArray
                // or : foreach varname inSortedView myview
                // or : foreach varname inFilteredView myview
                // or : foreach varname inPagedView myview
                // or : foreach varname inView myview
                paramRegexp : /^([_\w]+)\s+(\w+)\s+([\s\S]+)$/,
                process : function (out, statement, param) {
                    const variterset = out.newVarName();
                    const varitervalue = param[1];
                    // TODO:ModernAria: Implement isJsReservedWord and implement variable assignment
                    // if (Aria.isJsReservedWord(varitervalue)) {
                    //     return out.logError(statement, statementsSingleton.INCORRECT_VARIABLE_NAME, [varitervalue]);
                    // }
                    let inKeyWord = param[2];
                    if (inKeyWord != "in" && inKeyWord != "inArray" && inKeyWord != "inView"
                            && inKeyWord != "inSortedView" && inKeyWord != "inFilteredView"
                            && inKeyWord != "inPagedView") {
                        return out.logError(statement, statementsSingleton.INVALID_FOREACH_INKEYWORD, [inKeyWord]);
                    }
                    const iteratesView = (inKeyWord != "in" && inKeyWord != "inArray");
                    if (inKeyWord == "inView") {
                        inKeyWord = "inPagedView";
                    }
                    let iteratedObject = param[3];
                    statement.properties = {
                        variable: varitervalue,
                        inKeyWord: inKeyWord,
                        iteratedObject: iteratedObject
                    };
                    const variterindex = varitervalue + "_index";
                    if (out.debug) {
                        iteratedObject = out.wrapExpression(iteratedObject, statement, "this.ITERABLE_UNDEFINED");
                    }

                    out.writeln("var ", variterset, "=(", iteratedObject, ");");

                    out.writeln("if(", iteratedObject, "==undefined){");
                    out.increaseIndent();
                    out.writeln("this.$logError(this.ITERABLE_UNDEFINED,[", out.stringify(statement.name), ",__filename, ", statement.lineNumber, "]);");
                    out.decreaseIndent();
                    out.writeln("}");

                    const variterct = varitervalue + "_ct";
                    statement[FRAMEWORK_PREFIX + 'foreachCounter'] = variterct; // for the separator statement
                    out.writeln("var ", variterct, "=0;");
                    let varLastIndex;
                    if (iteratesView) {
                        varLastIndex = out.newVarName();
                        out.writeln(variterset, ".refresh();");
                        if (inKeyWord == "inPagedView") {
                            var varCurrentPageIndex = out.newVarName();
                            out.writeln("var ", varCurrentPageIndex, "=", variterset, ".currentPageIndex;");
                            out.writeln("var ", varLastIndex, "=", variterset, ".pages[", varCurrentPageIndex, "].lastItemIndex;");
                            out.writeln("for (var ", variterindex, "=", variterset, ".pages[", varCurrentPageIndex, "].firstItemIndex;", variterindex, "<=", varLastIndex, ";", variterindex, "++) {");
                        } else {
                            out.writeln("var ", varLastIndex, "=", variterset, ".items.length;");
                            out.writeln("for (var ", variterindex, "=0;", variterindex, "<", varLastIndex, ";", variterindex, "++) {");
                        }
                        out.increaseIndent();
                        out.writeln("var ", varitervalue, "_info=", variterset, ".items[", variterindex, "];");
                        if (inKeyWord == "inPagedView") {
                            out.writeln("if (", varitervalue, "_info.pageIndex==", varCurrentPageIndex, ") {");
                        } else if (inKeyWord == "inFilteredView") {
                            out.writeln("if (", varitervalue, "_info.filteredIn) {");
                        }
                        out.increaseIndent();
                        out.writeln("var ", varitervalue, "=", varitervalue, "_info.value;");
                    } else if (inKeyWord == "inArray") {
                        varLastIndex = out.newVarName();
                        out.writeln("var ", varLastIndex, "=", variterset, ".length;");
                        out.writeln("for (var ", variterindex, "=0;", variterindex, "<", varLastIndex, ";", variterindex, "++) {");
                        out.increaseIndent();
                        out.writeln("var ", varitervalue, "=", variterset, "[", variterindex, "];");
                    } else /* if (inKeyWord == "in") */{
                        out.writeln("for (var ", variterindex, " in ", variterset, ") {");
                        out.increaseIndent();
                        out.writeln("if (", variterset, ".hasOwnProperty(", variterindex, ") && !this.$json.isMetadata(", variterindex, ")) {");
                        out.increaseIndent();
                        out.writeln("var ", varitervalue, "=", variterset, "[", variterindex, "];");
                    }
                    out.writeln(variterct, "++;");
                    out.processContent(statement.content);
                    if (inKeyWord != "inSortedView" && inKeyWord != "inArray") {
                        out.decreaseIndent();
                        out.writeln("}");
                    }
                    out.decreaseIndent();
                    out.writeln("}");
                }
            },
            "repeater" : {
                inMacro : true,
                container : false,
                process : function (out: ClassWriter, statement: Statement) {
                    let param = statement.paramBlock;
                    if (out.debug) {
                        param = out.wrapExpression(param, statement, "this.EXCEPTION_IN_REPEATER_PARAMETER");
                    }
                    out.addDependency("aria.templates.Repeater"); // dependency on the Repeater object
                    out.writeln("this.__$statementRepeater(", statement.lineNumber, ",(", param, "));");
                }
            },
            "macro" : {
                inMacro : false,
                container : true,
                // Syntax: macro macroname ( macroparam1, macroparam2 ... )
                paramRegexp : /^([_\w]+)\s*\(\s*([_\w]+(?:\s*,\s*[_\w]+)*)?\s*\)\s*$/,
                process : function (out: ClassWriter, statement: Statement, param: string[]) {
                    const macroname = param[1];
                    const args = param[2] && param[2].split(/\s*,\s*/) || [];
                    currentMacroName = macroname;
                    const definedMacro = out.getMacro(macroname);
                    if (!definedMacro.definition) {
                        return out.logError(statement, MACRO_ALREADY_DEFINED, [macroname,
                                definedMacro.definition!.lineNumber]); //TODO:ModernAria:Check why automatic type narrowing not working
                    }
                    definedMacro.definition = statement;
                    out.enterBlock("prototype");
                    out.writeln("macro_", macroname, ": function (", args.join(","), ") {");
                    out.increaseIndent();
                    out.writeln("try {");
                    out.increaseIndent();
                    out.writeln("with (this) {");
                    out.increaseIndent();
                    statement.content && out.processContent(statement.content);
                    out.decreaseIndent();
                    out.writeln("}");
                    out.decreaseIndent();
                    out.writeln("} catch (_ex) {");
                    out.increaseIndent();
                    //TODO:ModernAria:Framework prefix constant should be in root Aria
                    out.writeln("this.$logError(this.EXCEPTION_IN_MACRO,[", stringify(macroname), ",__filename, this['"
                            + FRAMEWORK_PREFIX + "currentLineNumber']],_ex);");
                    out.decreaseIndent();
                    out.writeln("}");
                    if (globalMacroVariables.length > 0) {
                        out.writeln("var ", globalMacroVariables.join(", "), ";");
                        globalMacroVariables = [];
                    }
                    out.decreaseIndent();
                    out.writeln("},");
                    out.leaveBlock();
                    statement.properties = {
                        name: macroname,
                        args: args
                    };
                }
            },
            // "memo" : {
            //     inMacro : true,
            //     container : true,
            //     // Syntax: macro macroname ( macroparam1, macroparam2 ... )
            //     paramRegexp : /^[\S\s]*$/,
            //     process : function (out, statement, param) {
            //         out.processContent(statement.content);
            //     }
            // },
            // "call" : {
            //     inMacro : true,
            //     container : false,
            //     // Syntax: call macroname ( any params ... )
            //     // PTR 04231438: Regular expression must accept spaces at the end.
            //     paramRegexp : /^(\$?[_\w]+\.)?([_\w]+)\s*\(([\s\S]*)\)\s*$/,
            //     process : function (out, statement, param) {
            //         var macroContainer = param[1]; // macro container (with the dot at the end)
            //         var macroname = param[2];
            //         var macroparams = param[3];
            //         var macroRef;
            //         var macroCall;
            //         if (macroContainer) {
            //             macroRef = "this." + macroContainer + "macro_" + macroname;
            //             if (macroContainer.charAt(0) == "$") {
            //                 // call a macro from a parent template
            //                 macroCall = macroRef + ".apply(this,[" + macroparams + "]);";
            //             } else {
            //                 macroCall = macroRef + "(" + macroparams + ");";
            //             }
            //         } else {
            //             macroRef = "this.macro_" + macroname;
            //             macroCall = macroRef + "(" + macroparams + ");";
            //         }
            //         if (out.debug) {
            //             var macroDisplay = macroContainer ? macroContainer + macroname : macroname;
            //             out.writeln("if (", macroRef, " == null) {");
            //             out.increaseIndent();
            //             out.writeln('this.$logError(this.MACRO_NOT_FOUND,[__filename,', statement.lineNumber, ',', out.stringify(macroDisplay), ']);');
            //             out.decreaseIndent();
            //             out.writeln("}");
            //         }
            //         out.writeln(macroCall);
            //         statement.properties = {
            //             container: macroContainer ? macroContainer.slice(0, -1) : undefined, // macro container (without the dot at the end)
            //             name: macroname,
            //             args: macroparams
            //         };
            //     }
            // },
            "section" : {
                inMacro : true,
                container : false,
                process : function (out: ClassWriter, statement: Statement) {
                    const sectionParam = statement.paramBlock;
                    const content = statement.content || null;
                    if (content) {
                        counter++;
                        const macroName = automaticMacroPrefix + counter;
                        automaticMacroCounter++;

                        out.writeln("this.macro_", macroName, "= function (){");
                        out.increaseIndent();
                        out.writeln("try {");
                        out.increaseIndent();
                        statement.content && out.processContent(statement.content);
                        out.decreaseIndent();
                        out.writeln("} catch (_ex) {");
                        out.increaseIndent();
                        out.writeln("this.$logError(this.EXCEPTION_IN_MACRO,[", stringify(currentMacroName), ",__filename, this['"
                                + FRAMEWORK_PREFIX + "currentLineNumber']],_ex);");
                        out.decreaseIndent();
                        out.writeln("}");
                        out.decreaseIndent();
                        out.writeln("};");

                        const macroArg = '{name : "' + macroName + '", scope : this}';

                        out.writeln("this.__$insertSection(", `${statement.lineNumber}`, ",", sectionParam, ",", macroArg, ");");
                        automaticMacroCounter--;
                    } else {
                        out.writeln("this.__$insertSection(", `${statement.lineNumber}`, ",", sectionParam, ");");
                    }
                }
            },
            "var" : {
                inMacro : undefined, /* may be in or out of a macro */
                container : false,
                paramRegexp : /^([_\w]+)\s*=([\s\S]*)$/,
                process : function (out, statement, param) {

                    let varname = param[1];
                    let value = param[2];
                    // TODO:ModernAria: Implement isJsReservedWord and check if error handling is needed
                    // if (Aria.isJsReservedWord(varname)) {
                    //     return out.logError(statement, statementsSingleton.INCORRECT_VARIABLE_NAME, [varname]);
                    // }
                    if (out.isOutputReady()) {
                        // in a macro
                        if (out.debug) {
                            value = out.wrapExpression(value, statement, "this.EXCEPTION_IN_VAR_EXPRESSION");
                        }
                        let prefix = "var ";
                        if (automaticMacroCounter > 0) {
                            prefix = "";
                            globalMacroVariables.push(varname);
                        }
                        out.writeln(prefix, varname, "=(", value, ");");
                    } else {
                        // out of a macro
                        out.enterBlock("globalVars");
                        if (out.debug) {
                            value = out.wrapExpression(value, statement, "this.EXCEPTION_IN_VAR_EXPRESSION");
                        }
                        out.writeln("this.", varname, "=(", value, ");");
                        out.leaveBlock();
                    }
                    statement.properties = {
                        name: varname,
                        value: value
                    };
                }
            },
            "set" : {
                inMacro : true,
                container : false,
                paramRegexp : /^([_\w]+(?:\.[_\w]+)*)\s*([\+\-]?\=)([\s\S]*)$/,
                process : function (out: ClassWriter, statement: Statement, param: string[]) {
                    const varname = param[1];
                    const op = param[2];
                    let value = param[3];
                    const varnames = varname.split('.');
                    for (let i = 0, ii = varnames.length; i < ii; i++) {
                        // TODO:ModernAria: Implement isJsReservedWord and check if error handling is needed
                        // if (Aria.isJsReservedWord(varnames[i])) {
                        //     return out.logError(statement, INCORRECT_VARIABLE_NAME, [varname]);
                        // }
                    }
                    if (out.debug) {
                        value = out.wrapExpression(value, statement, "this.EXCEPTION_IN_SET_EXPRESSION");
                    }
                    out.writeln(varname, op, "(", value, ");");
                    statement.properties = {
                        name: varname,
                        operator: op,
                        value: value
                    };
                }
            },
            "checkDefault" : {
                inMacro : true,
                container : false,
                paramRegexp : /^([_\w]+)\s*\=([\s\S]*)$/,
                process : function (out: ClassWriter, statement: Statement, param: string[]) {
                    const varname = param[1];
                    let value = param[2];
                    // TODO:ModernAria: Implement isJsReservedWord and check if error handling is needed
                    // if (Aria.isJsReservedWord(varname)) {
                    //     return out.logError(statement, statementsSingleton.INCORRECT_VARIABLE_NAME, [varname]);
                    // }
                    if (out.debug) {
                        value = out.wrapExpression(value, statement, "this.EXCEPTION_IN_CHECKDEFAULT_EXPRESSION");
                    }
                    out.writeln("if (", varname, "===undefined) {");
                    out.increaseIndent();
                    out.writeln(varname, "=(", value, ");");
                    out.decreaseIndent();
                    out.writeln("}");
                    statement.properties = {
                        name: varname,
                        value: value
                    };
                }
            },
            // "@" : {
            //     inMacro : true,
            //     container : null, /* may be a container or not depending on the control */
            //     process : function (out: ClassWriter, statement: Statement) {
            //         const parsename = /^@(\w+):(\w+)$/.exec(statement.name);
            //         if (!parsename || parsename.length != 3) {
            //             return out.logError(statement, INVALID_WIDGET_SYNTAX);
            //         }
            //         let libName = parsename[1];
            //         let widgetName = parsename[2];
            //         let libclasspath = out.templateParam.$wlibs[libName];
            //         if (libclasspath === undefined) {
            //             return out.logError(statement, UNDECLARED_WIDGET_LIBRARY, [libName]);
            //         }
            //         if (!out.dontLoadWidgetLibs) {
            //             let wlib = out.wlibs[libName];
            //             if (!wlib) {
            //                 wlib = Aria.getClassRef(libclasspath);
            //                 if (!ariaUtilsType.isInstanceOf(wlib, "aria.widgetLibs.WidgetLib")) {
            //                     return out.logError(statement, statementsSingleton.INVALID_WIDGET_LIBRARY, [libName,
            //                             libclasspath]);
            //                 }
            //                 out.wlibs[libName] = wlib;
            //             }
            //             var dep = wlib.getWidgetDependencies(widgetName, out.allDependencies);
            //             if (!dep) {
            //                 return out.logError(statement, statementsSingleton.UNKNOWN_WIDGET, [statement.name]);
            //             }
            //             out.addDependencies(dep);
            //         }
            //         var param = statement.paramBlock;
            //         if (param.length === 0) {
            //             param = "undefined";
            //         } else {
            //             // Look for use of standard binding transforms
            //             // and automatically add those to dependencies
            //             var transformDependencies = [];
            //             var regEx = /[\'\"](aria\.widgets\.transform\.(.+))[\'\"]/g;
            //             var myMatch = regEx.exec(param);
            //             while (myMatch) {
            //                 transformDependencies.push(myMatch[1]);
            //                 myMatch = regEx.exec(param);
            //             }
            //             out.addDependencies(transformDependencies);
            //         }

            //         if (out.debug && param != "undefined") {
            //             param = out.wrapExpression(param, statement, "this.EXCEPTION_IN_CONTROL_PARAMETERS");
            //         }

            //         if (statement.content) {
            //             // container widget
            //             out.writeln("if (this.__$beginContainerWidget(", out.stringify(libclasspath), ",", out.stringify(widgetName), ",(", param, "),", statement.lineNumber, ")) {");
            //             out.increaseIndent();
            //             out.processContent(statement.content);
            //             out.writeln("this.__$endContainerWidget();");
            //             out.decreaseIndent();
            //             out.writeln("}");
            //         } else {
            //             // simple widget
            //             out.writeln("this.__$processWidgetMarkup(", out.stringify(libclasspath), ",", out.stringify(widgetName), ",(", param, "),", statement.lineNumber, ");");
            //         }
            //         statement.properties = {
            //             libName: libName,
            //             libClasspath: libclasspath,
            //             widgetName: widgetName
            //         };
            //     }
            // }
        };

//         ariaCoreAppEnvironment.$on({
//             "environmentChanged" : this.__onEnvironmentChanged,
//             scope : this
//         });

//     },
//     $destructor : function () {
//         ariaCoreAppEnvironment.$unregisterListeners(this);
//     },
//     $prototype : {

//         /**
//          * Check the application settings in order to ascertain whether it is possible to use sections as containers
//          * @return {Boolean}
//          * @private
//          */
//         __allowSectionsAsContainers : function () {
//             var allowSectionsAsContainers = ariaCoreEnvironmentEnvironment.checkApplicationSettings("templateSettings").allowSectionsAsContainers;

//             if (allowSectionsAsContainers) {
//                 this.$logWarn(this.SECTIONS_AS_CONTAINERS);
//             }
//             return allowSectionsAsContainers;

//         },

//         /**
//          * React to the change of the environment setting and update the "section" statement descript to allow/prevent
//          * to use sections as containers
//          */
//         __onEnvironmentChanged : function () {
//             this.ALLSTATEMENTS.section.container = this.__allowSectionsAsContainers() ? null : false;
//         }
//     }
// });
